[package]
name = "stackable-zookeeper-crd"
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Contains the Apache ZooKeeper CRD structs and utilities"
license = "OSL-3.0"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/stackabletech/zookeeper-operator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
serde_json = "1.0.70"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git" }
